version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: mediadb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Add this new line below. It maps our SQL file into a special Docker folder 
      # that automatically executes scripts on startup.
      - ./backend/infrastructure/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: